name: AI Inferencing Service Hands on Lab 
description: "Prototype to demonstrate Cloudera AI Inferencing Services in production"
author: "Cloudera"
date: "2025-02-13"
specification_version: 1.0
prototype_version: 1.0
# environment_variables:

#   CONNECTION_NAME:
#     default: "mlops-aw-dl"
#     description: "datalake connection name"
runtimes: 
  - editor: PBJ Workbench
    kernel: Python 3.10
    edition: Nvidia GPU
    version: "2024.10"
    
tasks:
  - type: run_session
    name: Install Dependencies
    script: install-dependencies.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 8
    
  - type: run_session
    name: load local data
    script: vector_db/html_to_text.py
    short_summary: Load local vector store
    kernel: python3
    cpu: 2
    memory: 8
